apiVersion: v1
kind: Service
metadata:
  labels:
    group: com.nullendpoint
    project: ${APPLICATION_NAME}
    provider: fabric8
    version: 1.0
  name: ${APPLICATION_NAME}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    group: com.nullendpoint
    project: ${APPLICATION_NAME}
    provider: fabric8
  sessionAffinity: None
  type: ClusterIP