---
apiVersion: "v1"
kind: "Template"
metadata:
  name: "fis2-generic-runtemplate"
  description: "A simple template for openshift to demonstrate a running a pod in a run namespace"
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
- description: IP for the openshift registry
  name: REGISTRY_IP
  required: true
- description: The namespace where the imagestream resides (usually the build namespace)
  name: IMAGESTREAM_NAMESPACE
  required: true
- description: The imagestream tag you wish to run in the run namespace
  name: IMAGESTREAM_TAG
  required: true
